name: build

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: set up jdk
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: set up gradle
        uses: gradle/actions/setup-gradle@v6

      - name: make gradlew executable
        run: chmod +x ./gradlew

      - name: build with gradle
        run: ./gradlew clean build shadowJar