name: release and publish to maven central

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build:
    name: build modules and release
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: set up jdk
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: set up gradle
        uses: gradle/actions/setup-gradle@v6

      - name: get version
        run: echo "PROJECT_VERSION=$(./gradlew -q properties --property version | awk '/^version:/ {print $2}')" >> $GITHUB_ENV

      - name: build modules
        run: ./gradlew clean build shadowJar

      - name: publish to central
        run: |
          ./gradlew \
            :custom-names-api:publishAllPublicationsToCentralPortal \
            :custom-names-minestom:publishAllPublicationsToCentralPortal
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - name: create github release
        run: |
          jars=()
          while IFS= read -r -d '' jar; do
            if [[ $(basename "$jar") =~ -[0-9]+\.[0-9]+ ]]; then
              echo "Skipping $jar due to version number"
            else
              echo "Uploading $jar"
              jars+=("$jar")
            fi
          done < <(find . -type f -path "*/build/libs/*.jar" -not -path "./build/libs/*" -print0)

          gh release create "v${PROJECT_VERSION}" \
            --target main \
            --title "v${PROJECT_VERSION}" \
            --generate-notes \
            "${jars[@]}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}